#!/usr/bin/env lua

-- This is only needed once to install the sketchybar module
-- (or for an update of the module)
-- os.execute("(git clone https://github.com/FelixKratz/SbarLua.git /tmp/SbarLua && cd /tmp/SbarLua/ && make install && rm -rf /tmp/SbarLua/)")

-- Add the sketchybar module to the package cpath (the module could be
-- installed into the default search path then this would not be needed)
package.cpath = package.cpath .. ";/Users/" .. os.getenv("USER") .. "/.local/share/sketchybar_lua/?.so"

-- Require the sketchybar module
sbar = require("sketchybar")

-- Specify which bar (only necessary if not default: sketchybar)
-- sbar.set_bar_name("bottom_bar")

-- Load the init.lua file
require("init")

sbar.hotload(true)

-- Run the event loop of the sketchybar module (without this there will be no
-- bi-directional communication between the lua module and sketchybar)
sbar.event_loop()
